package com.fasto.datamanager.dto.wrappers;

public enum RequestDtoWrapperType {
    CREATE_PLAYER,
    CREATE_ENTRY,
    HEADER_FETCH_CURRENT_PLAYER,
    LOGIN_PLAYER_SUBSCRIBE,
    UPCOMING_SUBSCRIBE,
    COMPLETED_SUBSCRIBE,
    FETCH_ENTRIES,
    CREATE_TOURNAMENT_TEMPLATE,
    CREATE_TOURNAMENT,
    STOCKS_HOLDER_SUBSCRIBE,
    TOURNAMENT_DETAILS_SUBSCRIBE,
    LINEUP_CREATE,
    LINEUP_UPDATE,
    LINEUP_DELETE,
    CREATE_SLATE,
    LOBBY_SUBSCRIBE,
    LIVE_SUBSCRIBE,
    TOURNAMENT_DETAILS_LINEUPS_SUBSCRIBE,
    LINEUP_CREATOR_CHANGE_STOCK_ITEMS_STATE,
    STOCKS_WATCHER_SUBSCRIBE,
    LOGIN_USER,
    LAUNCH
}
